CREATE DATABASE HOTELARIA;

USE HOTELARIA;


CREATE TABLE ENDERECO(   #OK
    ENDERECO_ID INT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR(255) NOT NULL,
    NUMERO VARCHAR(40) NOT NULL,
    COMPLEMENTO VARCHAR(40),
    BAIRRO VARCHAR(40) NOT NULL,
    CIDADE VARCHAR(60) NOT NULL,
    ESTADO ENUM('AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO') NOT NULL,
    CEP VARCHAR(20) NOT NULL
);


CREATE TABLE PESSOA(		#OK
    PESSOA_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    FIXO VARCHAR(13),
    CELULAR VARCHAR(13) NOT NULL,
    WHATSAPP BOOLEAN DEFAULT FALSE,
    OBSERVACOES VARCHAR(255),
    FK_ENDERECO INT NOT NULL,
    FOREIGN KEY (FK_ENDERECO)
    REFERENCES ENDERECO(ENDERECO_ID)
);

#ENUM() DEFAULT,

CREATE TABLE HOSPEDE_JURIDICO(		#OK
    HOSPEDE_JURIDICO_ID INT PRIMARY KEY AUTO_INCREMENT,
    RAZAO_SOCIAL VARCHAR(255) NOT NULL,
    CNPJ VARCHAR(18) UNIQUE NOT NULL,
    INSCRICAO_ESTADUAL VARCHAR(40),
    STATUS_EMPRESA ENUM('ATIVO', 'PRE_CADASTRADO', 'SEM_RESERVA' ) DEFAULT 'SEM_RESERVA' NOT NULL,
    TIPO_CONTRATO ENUM('CONVÊNIO', 'FATURADO', 'EMPRESA_PARCEIRA') DEFAULT 'FATURADO' NOT NULL,
    DATA_CADASTRO VARCHAR(10) NOT NULL,
    PREFERENCIA_CONTATO VARCHAR(255),
    RESPONSAVEL_FATURAMENTO VARCHAR(255),
    NOTAS_INTERNAS VARCHAR(255),
    FORMA_PAGAMENTO ENUM('BOLETO_BANCÁRIO', 'CARTÃO_CORPORATIVO', 'PIX_EMPRESARIAL', 'DEPÓSITO_EM_CONTA') DEFAULT 'PIX_EMPRESARIAL' NOT NULL,
    PRAZO_FATURAMENTO  ENUM('15_DIAS', '30_DIAS', '45_DIAS', '60_DIAS') DEFAULT '30_DIAS' NOT NULL,
    LIMITE_CREDITO DECIMAL(10,2) DEFAULT 0.00,
    INTERESSES VARCHAR(255),
	FK_PESSOA INT UNIQUE NOT NULL,
    FOREIGN KEY (FK_PESSOA)
    REFERENCES PESSOA(PESSOA_ID)
   );


CREATE TABLE HOSPEDE_FISICO (		#OK
    HOSPEDE_FISICO_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(40) NOT NULL,
    SOBRENOME VARCHAR(60) NOT NULL,
    DATA_NASCIMENTO VARCHAR(10) NOT NULL,
    GENERO ENUM('MASCULINO', 'FEMININO') DEFAULT 'MASCULINO' NOT NULL,
    CPF VARCHAR(11) UNIQUE NOT NULL,
    RG VARCHAR(20) NOT NULL,
    NATURALIDADE VARCHAR(50),
    ESTADO_CIVIL ENUM('CASADO', 'DIVORCIADO', 'SEPARADO', 'SOLTEIRO', 'VIUVO') DEFAULT 'SOLTEIRO',
    FOTO VARCHAR(255),
    PROFISSAO VARCHAR(100),
    STATUS_HOSPEDE ENUM ('ATIVO', 'PRE_CADASTRADO', 'SEM_RESERVA' ) DEFAULT 'SEM_RESERVA' NOT NULL,
    TIPO_DOC ENUM('CNH', 'PASSAPORTE', 'RG') DEFAULT 'CNH',
    NUMERO_DOC VARCHAR(20),
    ORGAO_EMISSOR VARCHAR(50),
    DATA_EMISSAO VARCHAR(10),
    DATA_CADASTRO VARCHAR(10) NOT NULL,
    PREFERENCIA_CONTATO VARCHAR(50),
    PREFERENCIA_QUARTO ENUM('SOLTEIRO', 'DUPLO', 'TRIPLO', 'QUÁDRUPLO', 'SUITE', 'DELUXE', 'EXECUTIVO', 'ADAPTADO', 'LUXO', 'FAMILIAR') DEFAULT 'SOLTEIRO',
    PREFERENCIA_ANDAR VARCHAR(2),
    ULTIMA_VISITA VARCHAR(10),
    PREFERENCIA_CAMA VARCHAR(20),
    ITENS_ESPECIAIS VARCHAR(255),
    INTERESSES VARCHAR(255),
    NOTAS_INTERNAS VARCHAR(255),
    #EMPRESA_VINCULADA ???
    #CNPJ ???
    CARGO VARCHAR(100),
    RESPONSAVEL_FATURAMENTO VARCHAR(100),
    FK_PESSOA INT UNIQUE NOT NULL,
    FOREIGN KEY (FK_PESSOA)
    REFERENCES PESSOA(PESSOA_ID)
    );


CREATE TABLE FUNCIONARIO(		#OK
    FUNCIONARIO_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(40) NOT NULL,
    SOBRENOME VARCHAR(60) NOT NULL,
    DATA_NASCIMENTO VARCHAR(10) NOT NULL,
    GENERO ENUM('MASCULINO', 'FEMININO') DEFAULT 'MASCULINO' NOT NULL,
    CPF VARCHAR(11) UNIQUE NOT NULL,
    RG VARCHAR(20) NOT NULL,
    NATURALIDADE VARCHAR(50),
    ESTADO_CIVIL ENUM('CASADO', 'DIVORCIADO', 'SEPARADO', 'SOLTEIRO', 'VIUVO') DEFAULT 'SOLTEIRO',
    FOTO VARCHAR(255),
    NOME_MAE VARCHAR(100) NOT NULL,
    NOME_PAI VARCHAR(100),
    MATRICULA INT UNIQUE NOT NULL,
    CARGO ENUM('GERENTE_GERAL', 'GERENTE_RH', 'RECEPCIONISTA', 'COPEIRO', 'AUXILIAR_DE_COZINHA', 'GARÇOM', 'BARISTA', 'CAMAREIRO', 'LAVANDERIA', 'ELETRICISTA', 'ENCANADOR', 'JARDINEIRO', 'FINANCEIRO', 'VIGIA', 'PORTEIRO') DEFAULT 'RECEPCIONISTA' NOT NULL,
    DEPARTAMENTO ENUM('GERÊNCIA', 'RECEPÇÃO', 'A&B', 'GOVERNANÇA', 'MANUTENÇÃO', 'MARKETING', 'RECURSOS HUMANOS', 'ADMINISTRATIVO', 'SEGURANÇA') DEFAULT 'RECEPÇÃO' NOT NULL,
    DATA_ADMISSAO VARCHAR(10) NOT NULL,
    JORNADA_TRABALHO INT NOT NULL,
    REGIME_CONTRATACAO ENUM('APREDIZAGEM', 'EXPERIENCIA', 'INTERMITENTE', 'PRAZO_DETERMINADO', 'PRAZO_INDETERMINADO', 'TEMPORÁRIO', 'ESTÁGIO') DEFAULT 'APRENDIZAGEM' NOT NULL,
    STATUS_FUNCIONARIO ENUM('ATIVO', 'INATIVO', 'LICENCIADO', 'AFASTADO') DEFAULT 'ATIVO' NOT NULL,
    SALARIO_BASE DECIMAL(10,2) NOT NULL CHECK (SALARIO_BASE >= 0),
    NUMERO_PIS VARCHAR(14) UNIQUE,
    CTPS VARCHAR(12) UNIQUE,
    HISTORICO VARCHAR(255),
    COMENTARIO_GESTAO VARCHAR(255),
    NOME_USUARIO VARCHAR(100) UNIQUE,
    SENHA VARCHAR(100),
    #graudeAcesso varchar(20) not null     ??????
    FK_PESSOA INT UNIQUE NOT NULL,
    FOREIGN KEY (FK_PESSOA)
    REFERENCES PESSOA (PESSOA_ID)

);


CREATE TABLE AUTENTICACAO ( 		#OK
    AUTENTICACAO_ID INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO VARCHAR(40) UNIQUE NOT NULL,
    SENHA VARCHAR(40) NOT NULL
);


CREATE TABLE CATEGORIA_QUARTO (		#OK
    CATEGORIA_QUARTO_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(255),
    CAPACIDADE_HOSPEDE INT NOT NULL CHECK (CAPACIDADE_HOSPEDE > 0),
    TIPO_QUARTO ENUM('SOLTEIRO', 'DUPLO', 'TRIPLO', 'QUÁDRUPLO', 'SUITE', 'DELUXE', 'EXECUTIVO', 'ADAPTADO', 'LUXO', 'FAMILIAR') DEFAULT 'SOLTEIRO' NOT NULL,
    TIPO_CAMA ENUM('CASAL', 'EXTRA', 'KING', 'QUEEN', 'SOLTEIRO', 'INFANTIL') DEFAULT 'SOLTEIRO' NOT NULL,
    QUANTIDADE_CAMA INT NOT NULL CHECK (QUANTIDADE_CAMA > 0),
    VALOR_BASE DECIMAL(10,2) NOT NULL CHECK (VALOR_BASE >= 0),
    STATUS_QUARTO ENUM('ATIVO', 'INATIVO') DEFAULT 'ATIVO' NOT NULL
);


CREATE TABLE QUARTO (		#OK
    QUARTO_ID INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO_QUARTO INT NOT NULL UNIQUE,
    ANDAR_QUARTO INT NOT NULL,
    STATUS_QUARTO ENUM('DISPONIVEL', 'OCUPADO', 'LIMPEZA', 'RESERVADO', 'INTERDITADO') DEFAULT 'DISPONIVEL' NOT NULL,
    RESTRICOES VARCHAR(255),
    OUTRAS_COMODIDADES VARCHAR(255),
    FRIGOBAR BOOLEAN DEFAULT FALSE,
    SMART_TV BOOLEAN DEFAULT FALSE,
    AR_CONDICIONADO BOOLEAN DEFAULT FALSE,
    BANHEIRA BOOLEAN DEFAULT FALSE,
    VARANDA BOOLEAN DEFAULT FALSE,
    MICROONDAS BOOLEAN DEFAULT FALSE,
    FOGAO BOOLEAN DEFAULT FALSE,
    TV_CABO BOOLEAN DEFAULT FALSE,
    GUARDA_ROUPA BOOLEAN DEFAULT FALSE,
    ACESSIBILIDADE BOOLEAN DEFAULT FALSE,
    TAMANHO_QUARTO DECIMAL(7,2) CHECK (TAMANHO_QUARTO >= 0),
    PRECO_DIARIA DECIMAL(10,2) NOT NULL CHECK (PRECO_DIARIA >= 0),
    TIPO_COBRANCA ENUM('POR_PESSOA', 'POR_QUARTO', 'PACOTE') DEFAULT 'POR_QUARTO',
    DATA_ULTIMO_USO DATE,
    DATA_ULTIMA_LIMPEZA DATE,
    DATA_ULTIMA_MANUTENCAO DATE,
    STATUS_MANUTENCAO ENUM('EM_DIA', 'EM_MANUTENCAO', 'NECESSITA_REPARO') DEFAULT 'EM_DIA' NOT NULL,
    NECESSITA_LIMPEZA BOOLEAN DEFAULT FALSE,
    OBSERVACOES_GERAIS VARCHAR(255),
    DESCRICAO_COMPLEMENTAR VARCHAR(255),
    OBSERVACOES_INTERNAS VARCHAR(255),
    COMENTARIOS_AUDITORIA VARCHAR(255),
    FK_CATEGORIA_QUARTO INT NOT NULL,    
    FOREIGN KEY (FK_CATEGORIA_QUARTO) 
    REFERENCES CATEGORIA_QUARTO(CATEGORIA_QUARTO_ID)

);


CREATE TABLE FORNECEDOR (		#OK
    FORNECEDOR_ID INT PRIMARY KEY AUTO_INCREMENT,
    RAZAO_SOCIAL VARCHAR(255) NOT NULL,
    CNPJ VARCHAR(18) UNIQUE NOT NULL,
    INSCRICAO_ESTADUAL VARCHAR(40),
    STATUS_FORNECEDOR ENUM('ATIVO', 'INATIVO') DEFAULT 'ATIVO' NOT NULL,
    CATEGORIA_PRODUTO ENUM('ACESSORIOS', 'ALIMENTOS', 'BEBIDAS', 'CONFORTO', 'ELETRONICOS', 'HIGIENE', 'SEGURANCA') DEFAULT 'ACESSORIOS' NOT NULL,
    DATA_CADASTRO VARCHAR(10) NOT NULL,
    PREFERENCIA_CONTATO VARCHAR(255),
    NOME_REPRESENTANTE VARCHAR(255),
    SITE VARCHAR(100),
    NOTAS_INTERNAS VARCHAR(255),
    FORMA_PAGAMENTO ENUM('BOLETO_BANCÁRIO', 'CARTÃO_CORPORATIVO', 'PIX_EMPRESARIAL', 'DEPÓSITO_EM_CONTA') DEFAULT 'PIX_EMPRESARIAL' NOT NULL,
    PRAZO_FATURAMENTO  ENUM('15_DIAS', '30_DIAS', '45_DIAS', '60_DIAS') DEFAULT '30_DIAS' NOT NULL,
    FK_ENDERECO INT NOT NULL,
    FOREIGN KEY (FK_ENDERECO)
    REFERENCES ENDERECO(ENDERECO_ID)
    
);


CREATE TABLE PRODUTO (		#OK
    PRODUTO_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PRODUTO VARCHAR(100) NOT NULL UNIQUE,
    DESCRICAO_PRODUTO VARCHAR(255),
    CATEGORIA ENUM('ACESSORIOS', 'ALIMENTOS', 'BEBIDAS', 'CONFORTO', 'ELETRONICOS', 'HIGIENE', 'SEGURANCA') DEFAULT 'ACESSORIOS' NOT NULL,
    MARCA VARCHAR(100),
    IMAGEM VARCHAR(255),
    QUANTIDADE_ESTOQUE INT DEFAULT 0 CHECK (QUANTIDADE_ESTOQUE >= 0),
    ESTOQUE_MINIMO INT DEFAULT 0 CHECK (ESTOQUE_MINIMO >= 0),
    ESTOQUE_MAXIMO INT CHECK (ESTOQUE_MAXIMO >= 0),
    LOCALIZACAO_ESTOQUE VARCHAR(100),
    PRECO_CUSTO DECIMAL(10,2) DEFAULT 0 CHECK (PRECO_CUSTO >= 0),
    PRECO_VENDA DECIMAL(10,2) NOT NULL CHECK (PRECO_VENDA >= 0),
    DESCONTO DECIMAL(5,2) DEFAULT 0 CHECK (DESCONTO >= 0),
    DATA_FABRICACAO VARCHAR(10),
    DATA_VALIDADE VARCHAR(10),
    STATUS_PRODUTO ENUM('DISPONIVEL', 'INDISPONIVEL', 'ESGOTADO', 'DESCONTINUADO', 'EM_REPOSICAO') DEFAULT 'DISPONIVEL' NOT NULL,
    GARANTIA VARCHAR(100),
    OBSERVACOES VARCHAR(255)
    
);  


CREATE TABLE SERVICO (		#OK
    SERVICO_ID INT PRIMARY KEY AUTO_INCREMENT,
    CODIGO_SERVICO INT NOT NULL UNIQUE,
    NOME_SERVICO VARCHAR(100) NOT NULL UNIQUE,
    CATEGORIA ENUM('LIMPEZA', 'ALIMENTACAO', 'LAZER', 'TRANSPORTE', 'EVENTOS') DEFAULT 'LAZER' NOT NULL,
    DESCRICAO VARCHAR(255),
    LOCAL_PRESTACAO VARCHAR(255),
    TEMPO_MEDIO_EXECUCAO VARCHAR(20),
    STATUS_SERVICO ENUM('ATIVO', 'INATIVO') DEFAULT 'ATIVO' NOT NULL,
    PRECO_BASE DECIMAL(10,2) NOT NULL CHECK (PRECO_BASE >= 0),
    TAXAS_ADICIONAIS DECIMAL(10,2) DEFAULT 0 CHECK (TAXAS_ADICIONAIS >= 0),
    FORMA_PAGAMENTO VARCHAR(30),
    CUSTO_OPERACIONAL DECIMAL(10,2) DEFAULT 0 CHECK (CUSTO_OPERACIONAL >= 0),
    DESCONTO DECIMAL(10,2) DEFAULT 0 CHECK (DESCONTO >= 0),
    HORARIOS_DISPONIVEIS VARCHAR(50),
    DIAS_SEMANA VARCHAR(50),
    CAPACIDADE_MAXIMA INT CHECK (CAPACIDADE_MAXIMA >= 0),
    ANTECEDENCIA_MINIMA INT CHECK (ANTECEDENCIA_MINIMA >= 0),
    FUNCIONARIO_RESPONSAVEL VARCHAR(100),
    RECURSOS_NECESSARIOS VARCHAR(255),
    IDADE_MINIMA INT CHECK (IDADE_MINIMA >= 0),
    ACESSIBILIDADE VARCHAR(100),
    RESTRICOES_SAUDE VARCHAR(255),
    OBSERVACOES VARCHAR(255)    
);


CREATE TABLE RESERVA(
    RESERVA_ID INT PRIMARY KEY AUTO_INCREMENT,
    DATA_CHECK_IN DATE NOT NULL,
    DATA_CHECK_OUT DATE NOT NULL,
    STATUS_RESERVA ENUM('CONFIRMADA', 'PENDENTE', 'CANCELADA', 'CHECK-IN', 'CHECK-OUT', 'NO-SHOW') DEFAULT 'PENDENTE' NOT NULL,
    DATA_RESERVA DATE,
    TIPO_RESERVA ENUM('DIRETA', 'AGENCIA', 'ONLINE', 'CORPORATIVA', 'PACOTE') DEFAULT 'DIRETA' NOT NULL,
    FORMA_PAGAMENTO ENUM('CRÉDITO', 'DÉBITO', 'PIX', 'BOLETO', 'DINHEIRO', 'TRANSFERÊNCIA', 'FATURADO') DEFAULT 'CRÉDITO',
    VALOR_TOTAL DECIMAL(12,2) NOT NULL,
    VALOR_DESCONTO DECIMAL(10,2) DEFAULT 0.00,
    TAXAS_ADICIONAIS DECIMAL(10,2) DEFAULT 0.00,
    OBSERVACOES TEXT,
    FK_HOSPEDE_FISICO INT,
    FK_HOSPEDE_JURIDICO INT,
    FOREIGN KEY (FK_HOSPEDE_FISICO)
    REFERENCES HOSPEDE_FISICO(HOSPEDE_FISICO_ID),
    FOREIGN KEY (FK_HOSPEDE_JURIDICO)
    REFERENCES HOSPEDE_JURIDICO(HOSPEDE_JURIDICO_ID)

);


CREATE TABLE RESERVA_QUARTO (
    RESERVA_QUARTO_ID INT PRIMARY KEY AUTO_INCREMENT,
    ADULTOS INT DEFAULT 1,
    CRIANCAS INT DEFAULT 0,
    VALOR_DIARIA DECIMAL(10,2) NOT NULL CHECK (VALOR_DIARIA >= 0),
    QUANTIDADE_DIAS INT NOT NULL CHECK (QUANTIDADE_DIAS > 0),
    DESCONTO DECIMAL(10,2) DEFAULT 0 CHECK (DESCONTO >= 0),
    OBSERVACOES VARCHAR(255),
    FK_RESERVA INT NOT NULL,
    FK_QUARTO INT NOT NULL,
    FOREIGN KEY (FK_RESERVA) REFERENCES RESERVA(RESERVA_ID),
    FOREIGN KEY (FK_QUARTO) REFERENCES QUARTO(QUARTO_ID)
);


CREATE TABLE MANUTENCAO (
    MANUTENCAO_ID INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_MANUTENCAO ENUM('PREVENTIVA', 'CORRETIVA', 'URGENTE', 'MELHORIA') NOT NULL,
    DATA_ABERTURA DATE NOT NULL,
    DATA_CONCLUSAO DATE,
    STATUS ENUM('ABERTA', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA') DEFAULT 'ABERTA' NOT NULL,
    DESCRICAO_PROBLEMA TEXT NOT NULL,
    SOLUCAO_APLICADA TEXT,
    PRIORIDADE ENUM('BAIXA', 'MEDIA', 'ALTA', 'URGENTE') DEFAULT 'MEDIA' NOT NULL,
    FUNCIONARIO_RESPONSAVEL VARCHAR(100),
    GARANTIA VARCHAR(100),
    OBSERVACOES TEXT,
    FK_QUARTO INT NOT NULL,
    FK_FUNCIONARIO INT NOT NULL,
    FOREIGN KEY (FK_QUARTO)
    REFERENCES QUARTO(QUARTO_ID),
    FOREIGN KEY (FK_FUNCIONARIO)
    REFERENCES FUNCIONARIO(FUNCIONARIO_ID)
);


CREATE TABLE FATURA (
    FATURA_ID INT PRIMARY KEY AUTO_INCREMENT,
    NUMERO_FATURA VARCHAR(20) UNIQUE NOT NULL,
    DATA_EMISSAO DATE NOT NULL,
    DATA_VENCIMENTO DATE NOT NULL,
    STATUS ENUM('ABERTA', 'PAGA', 'VENCIDA', 'CANCELADA', 'PARCIAL') DEFAULT 'ABERTA' NOT NULL,
    VALOR_TOTAL DECIMAL(12,2) NOT NULL,
    VALOR_PAGO DECIMAL(12,2) DEFAULT 0.00,
    DESCONTO DECIMAL(10,2) DEFAULT 0.00,
    OBSERVACOES TEXT,
    FORMA_PAGAMENTO ENUM('CRÉDITO', 'DÉBITO', 'PIX', 'BOLETO', 'DINHEIRO', 'TRANSFERÊNCIA', 'FATURADO') DEFAULT 'CRÉDITO',
	FK_RESERVA INT NOT NULL,
    FOREIGN KEY (FK_RESERVA)
    REFERENCES RESERVA(RESERVA_ID)

);


CREATE TABLE PAGAMENTO (
    PAGAMENTO_ID INT PRIMARY KEY AUTO_INCREMENT,
    DATA_PAGAMENTO DATE NOT NULL,
    VALOR_PAGO DECIMAL(10,2) NOT NULL,
    FORMA_PAGAMENTO ENUM('CRÉDITO', 'DÉBITO', 'PIX', 'BOLETO', 'DINHEIRO', 'TRANSFERÊNCIA') NOT NULL,
    STATUS_PAGAMENTO ENUM('CONFIRMADO', 'PENDENTE', 'CANCELADO', 'ESTORNADO') DEFAULT 'CONFIRMADO' NOT NULL,
    NUMERO_TRANSACAO VARCHAR(50),
    BANCO VARCHAR(50),
    AGENCIA VARCHAR(20),
    CONTA VARCHAR(20),
    TITULAR VARCHAR(100),
    OBSERVACOES TEXT,
	FK_FATURA INT NOT NULL,
    FOREIGN KEY (FK_FATURA)
    REFERENCES FATURA(FATURA_ID)


);




CREATE TABLE CONSUMO (
    CONSUMO_ID INT PRIMARY KEY AUTO_INCREMENT,
    DATA_CONSUMO DATETIME DEFAULT CURRENT_TIMESTAMP,
    QUANTIDADE INT DEFAULT 1 NOT NULL,
    VALOR_UNITARIO DECIMAL(10,2) NOT NULL,
    VALOR_TOTAL DECIMAL(10,2),
    STATUS ENUM('PENDENTE', 'FATURADO', 'CANCELADO') DEFAULT 'PENDENTE' NOT NULL,
    OBSERVACOES TEXT,
    FK_RESERVA INT NOT NULL,
    FK_QUARTO INT NOT NULL,
    FK_PRODUTO INT,
    FK_SERVICO INT,
    FOREIGN KEY (FK_RESERVA)
    REFERENCES RESERVA(RESERVA_ID),
    FOREIGN KEY (FK_QUARTO)
    REFERENCES QUARTO(QUARTO_ID),
    FOREIGN KEY (FK_PRODUTO)
    REFERENCES PRODUTO(PRODUTO_ID),
    FOREIGN KEY (FK_SERVICO)
    REFERENCES SERVICO(SERVICO_ID)
);





















