/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Érica_Almeida
 */
public class TelaLogoff extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaLogoff
     */
    public TelaLogoff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMensagemdeconfirmacao = new javax.swing.JLabel();
        btnSimsair = new javax.swing.JButton();
        btnNaosair = new javax.swing.JButton();

        setClosable(true);
        setTitle("Confirmação");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMensagemdeconfirmacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMensagemdeconfirmacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-informacao20x20.png"))); // NOI18N
        lblMensagemdeconfirmacao.setText("Deseja trocar de Usuário?");

        btnSimsair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-confirmar20x20.png"))); // NOI18N
        btnSimsair.setText("Sim");
        btnSimsair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimsairActionPerformed(evt);
            }
        });

        btnNaosair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNaosair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-cancelar20x20.png"))); // NOI18N
        btnNaosair.setText("Não");
        btnNaosair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNaosair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNaosairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSimsair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNaosair))
                    .addComponent(lblMensagemdeconfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblMensagemdeconfirmacao)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimsair)
                    .addComponent(btnNaosair))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 263, 210);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimsairActionPerformed
        TelaLogin tela = new TelaLogin ();
        tela.setVisible(true);     
        
        this.dispose();
    }//GEN-LAST:event_btnSimsairActionPerformed

    private void btnNaosairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNaosairActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNaosairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNaosair;
    private javax.swing.JButton btnSimsair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMensagemdeconfirmacao;
    // End of variables declaration//GEN-END:variables
}
