package br.com.pensaosalvatore.sistema_hotelaria.desktop.view.principal;

import br.com.pensaosalvatore.sistema_hotelaria.desktop.controller.principal.PrincipalController;
import br.com.pensaosalvatore.sistema_hotelaria.modelo.dto.Usuario;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author Érica_Almeida
 */
public class PrincipalView extends javax.swing.JFrame {

    private final PrincipalController controller;
    private String LblNomedousuario;

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView(Usuario usuario) {
        this.LblNomedousuario = usuario.getUsuario();
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        controller = new PrincipalController(this, usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        telaFundo = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        lblNomedousuario = new javax.swing.JLabel();
        btnLogoff = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCadastro = new javax.swing.JMenu();
        miHospede = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        miQuarto = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        miUsuario = new javax.swing.JMenuItem();
        mnReservas = new javax.swing.JMenu();
        miRealizarreserva = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        miRelatorioreservas = new javax.swing.JMenuItem();
        mnConsultas = new javax.swing.JMenu();
        miConsultarhospede = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        miConsultarquartos = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        miConsultarreservas = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        miConsultarusuario = new javax.swing.JMenuItem();
        mnFerramentas = new javax.swing.JMenu();
        miSobre = new javax.swing.JMenuItem();
        mnSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel ABEF - Principal");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(0, 0));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel2.setText("                                                                                      Hotel ABEF - Todos os direitos reservados 2025");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        telaFundo.setBackground(new java.awt.Color(223, 176, 95));
        telaFundo.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/principal.png"))); // NOI18N

        telaFundo.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout telaFundoLayout = new javax.swing.GroupLayout(telaFundo);
        telaFundo.setLayout(telaFundoLayout);
        telaFundoLayout.setHorizontalGroup(
            telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaFundoLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        telaFundoLayout.setVerticalGroup(
            telaFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-logo-hotel_abef100x100.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("Hotel ABEF");

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-hora20x20.png"))); // NOI18N
        jLabel5.setText("Hora");

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-calendario20x20.png"))); // NOI18N
        jLabel6.setText("Data");

        lblNomedousuario.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N

        btnLogoff.setBackground(new java.awt.Color(255, 146, 47));
        btnLogoff.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        btnLogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-logout20x20.png"))); // NOI18N
        btnLogoff.setText("Logoff");
        btnLogoff.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLogoff.setContentAreaFilled(false);
        btnLogoff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(lblNomedousuario, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblNomedousuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(545, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(223, 176, 95));
        jMenuBar1.setFocusable(false);
        jMenuBar1.setRequestFocusEnabled(false);
        jMenuBar1.setSelectionModel(null);

        mnCadastro.setBackground(new java.awt.Color(223, 176, 95));
        mnCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-cadastro32x32.png"))); // NOI18N
        mnCadastro.setText("     Cadastro          |");
        mnCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnCadastro.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        mnCadastro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        miHospede.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        miHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-hospede20x20.png"))); // NOI18N
        miHospede.setText("Hóspede");
        miHospede.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHospedeActionPerformed(evt);
            }
        });
        mnCadastro.add(miHospede);
        mnCadastro.add(jSeparator6);

        miQuarto.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        miQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-quartos20x20.png"))); // NOI18N
        miQuarto.setText("Quartos");
        miQuarto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miQuartoActionPerformed(evt);
            }
        });
        mnCadastro.add(miQuarto);
        mnCadastro.add(jSeparator7);

        miUsuario.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        miUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-funcionario20x20.png"))); // NOI18N
        miUsuario.setText("Usuário");
        miUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUsuarioActionPerformed(evt);
            }
        });
        mnCadastro.add(miUsuario);

        jMenuBar1.add(mnCadastro);

        mnReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-reservas32x32.png"))); // NOI18N
        mnReservas.setText("     Reservas          |");
        mnReservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnReservas.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        miRealizarreserva.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        miRealizarreserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-reservas_futuras20x20.png"))); // NOI18N
        miRealizarreserva.setText("Realizar Reserva");
        miRealizarreserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miRealizarreserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRealizarreservaActionPerformed(evt);
            }
        });
        mnReservas.add(miRealizarreserva);
        mnReservas.add(jSeparator11);

        miRelatorioreservas.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        miRelatorioreservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-relatorio_reservas20x20.png"))); // NOI18N
        miRelatorioreservas.setText("Relatórios de Reservas");
        miRelatorioreservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnReservas.add(miRelatorioreservas);

        jMenuBar1.add(mnReservas);
        mnReservas.getAccessibleContext().setAccessibleDescription("");

        mnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-lupa32x32.png"))); // NOI18N
        mnConsultas.setText("    Consultas          |");
        mnConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnConsultas.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        miConsultarhospede.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        miConsultarhospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-consultar_pessoa20x20.png"))); // NOI18N
        miConsultarhospede.setText("Hóspedes");
        miConsultarhospede.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnConsultas.add(miConsultarhospede);
        mnConsultas.add(jSeparator8);

        miConsultarquartos.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        miConsultarquartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-quartos_ocupados20x20.png"))); // NOI18N
        miConsultarquartos.setText("Quartos");
        miConsultarquartos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnConsultas.add(miConsultarquartos);
        mnConsultas.add(jSeparator10);

        miConsultarreservas.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        miConsultarreservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-consultar_reserva20x20.png"))); // NOI18N
        miConsultarreservas.setText("Reservas");
        miConsultarreservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnConsultas.add(miConsultarreservas);
        mnConsultas.add(jSeparator9);

        miConsultarusuario.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        miConsultarusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-fornecedor20x20.png"))); // NOI18N
        miConsultarusuario.setText("Usuários");
        miConsultarusuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnConsultas.add(miConsultarusuario);

        jMenuBar1.add(mnConsultas);

        mnFerramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-ferramentas32x32.png"))); // NOI18N
        mnFerramentas.setText("     Ferramentas          |");
        mnFerramentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnFerramentas.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        miSobre.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        miSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-sobre_sistema20x20.png"))); // NOI18N
        miSobre.setText("Sobre");
        miSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnFerramentas.add(miSobre);

        jMenuBar1.add(mnFerramentas);

        mnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-sair32x32.png"))); // NOI18N
        mnSair.setText("     Sair          ");
        mnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnSair.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jMenuBar1.add(mnSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(telaFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 1662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(telaFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1936, 1089));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoffActionPerformed


    }//GEN-LAST:event_btnLogoffActionPerformed

    private void miRealizarreservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRealizarreservaActionPerformed

    }//GEN-LAST:event_miRealizarreservaActionPerformed

    private void miHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHospedeActionPerformed
    }//GEN-LAST:event_miHospedeActionPerformed

    private void miQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miQuartoActionPerformed
    }//GEN-LAST:event_miQuartoActionPerformed

    private void miUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUsuarioActionPerformed
    }//GEN-LAST:event_miUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    public JButton getBtnLogoff() {
        return btnLogoff;
    }

    public JMenuItem getMiSobre() {
        return miSobre;
    }

    public JMenuItem getMiHospede() {
        return miHospede;
    }

    public JMenuItem getMiUsuario() {
        return miUsuario;
    }

    public JLabel getLblNomedousuario() {
        return lblNomedousuario;
    }

    public JMenuItem getMiQuarto() {
        return miQuarto;
    }

    public JMenuItem getMiRealizarreserva() {
        return miRealizarreserva;
    }

    public JMenuItem getMiRelatorioreservas() {
        return miRelatorioreservas;
    }

    public JMenu getMnCadastro() {
        return mnCadastro;
    }

    public JMenu getMnConsultas() {
        return mnConsultas;
    }

    public JMenu getMnFerramentas() {
        return mnFerramentas;
    }

    public JMenu getMnReservas() {
        return mnReservas;
    }

    public JMenu getMnSair() {
        return mnSair;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogoff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JLabel lblNomedousuario;
    private javax.swing.JMenuItem miConsultarhospede;
    private javax.swing.JMenuItem miConsultarquartos;
    private javax.swing.JMenuItem miConsultarreservas;
    private javax.swing.JMenuItem miConsultarusuario;
    private javax.swing.JMenuItem miHospede;
    private javax.swing.JMenuItem miQuarto;
    private javax.swing.JMenuItem miRealizarreserva;
    private javax.swing.JMenuItem miRelatorioreservas;
    private javax.swing.JMenuItem miSobre;
    private javax.swing.JMenuItem miUsuario;
    private javax.swing.JMenu mnCadastro;
    private javax.swing.JMenu mnConsultas;
    private javax.swing.JMenu mnFerramentas;
    private javax.swing.JMenu mnReservas;
    private javax.swing.JMenu mnSair;
    public javax.swing.JDesktopPane telaFundo;
    // End of variables declaration//GEN-END:variables
}
